// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
        
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCADqX9HSmFpf_BAsqahodB3SBU_MDDHRY',
    appId: '1:340962842161:web:ae4c8feac16a05ce63a710',
    messagingSenderId: '340962842161',
    projectId: 'pro-task-d25ab',
    authDomain: 'pro-task-d25ab.firebaseapp.com',
    storageBucket: 'pro-task-d25ab.firebasestorage.app',
    measurementId: 'G-11SEP47RMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRKV0G1-zgjOQAIrXHd9KDJHzR0F_1z0',
    appId: '1:340962842161:android:8437a9e3fce5c76863a710',
    messagingSenderId: '340962842161',
    projectId: 'pro-task-d25ab',
    storageBucket: 'pro-task-d25ab.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1MSsgT0KAQBvue0EinNC8SiPDc2QuOQg',
    appId: '1:340962842161:ios:1c62e2096c89fa1163a710',
    messagingSenderId: '340962842161',
    projectId: 'pro-task-d25ab',
    storageBucket: 'pro-task-d25ab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1MSsgT0KAQBvue0EinNC8SiPDc2QuOQg',
    appId: '1:340962842161:ios:1c62e2096c89fa1163a710',
    messagingSenderId: '340962842161',
    projectId: 'pro-task-d25ab',
    storageBucket: 'pro-task-d25ab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCADqX9HSmFpf_BAsqahodB3SBU_MDDHRY',
    appId: '1:340962842161:web:68bc3b04666b4cb763a710',
    messagingSenderId: '340962842161',
    projectId: 'pro-task-d25ab',
    authDomain: 'pro-task-d25ab.firebaseapp.com',
    storageBucket: 'pro-task-d25ab.firebasestorage.app',
    measurementId: 'G-61EY0990BV',
  );

}